- name: Demo on tags
  hosts: localhost
  tasks:
    - name: fruits
      debug:
        msg: fruits
      tags:
        - fruits
        - fruit

    - name: groceries
      debug:
        msg: groceries
      tags:
        - groceries
        - cerals
# Tags can be applied on plays in playbook