- name: Setup Frontend
  hosts: frontend
  become: true
  tags: frontend
  roles:
    - frontend

- name: Setup MongoDB
  hosts: mongodb
  become: true
  tags: mongodb
  roles:
    - mongodb

- name: Setup Catalogue
  hosts: catalogue
  become: true
  tags: catalogue
  roles:
    - catalogue

- name: Setup Redis
  hosts: redis
  become: true
  tags: redis
  roles:
    - redis

- name: Setup User
  hosts: user
  become: true
  tags: user
  roles:
    - user

- name: Setup Cart
  hosts: cart
  become: true
  tags: cart
  roles:
    - cart

- name: Setup MySQL
  hosts: mysql
  become: true
  tags: mysql
  roles:
    - mysql

- name: Setup Shipping
  hosts: shipping
  become: true
  tags: shipping
  roles:
    - shipping
#
#- name: Setup RabbitMQ
#  hosts: rabbitmq
#  become: true
#  tags: rabbitmq
#  roles:
#    - rabbitmq
#
#- name: Setup Payment
#  hosts: payment
#  become: true
#  tags: payment
#  roles:
#    - payment
